version: '2'
services:
    first-app:
        image: first
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://first-postgresql:5432/first
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    first-postgresql:
        extends:
            file: postgresql.yml
            service: first-postgresql
