version: '2'
services:
    first-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/first/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=first
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
